// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/// @title IZKVerifier
/// @notice Interface for verifying Zero-Knowledge proofs generated by Noir circuits
/// @dev This interface will be implemented by the verifier contract generated by Noir
interface IZKVerifier {
    /// @notice Verifies a ZK proof
    /// @param proof The serialized proof bytes
    /// @param publicInputs The public inputs to the circuit (threshold as Field)
    /// @return valid Whether the proof is valid
    function verify(bytes calldata proof, uint256[] calldata publicInputs)
        external
        view
        returns (bool valid);
}

