// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {IZKVerifier} from "../interfaces/IZKVerifier.sol";

/// @title MockZKVerifier
/// @notice Mock verifier for testing purposes
/// @dev This is a placeholder that always returns true for testing
/// @dev In production, replace this with the actual verifier contract generated by Noir
contract MockZKVerifier is IZKVerifier {
    /// @notice Mock verification - always returns true for testing
    /// @param proof The serialized proof bytes (not validated in mock)
    /// @param publicInputs The public inputs (not validated in mock)
    /// @return valid Always returns true in mock mode
    function verify(bytes calldata proof, uint256[] calldata publicInputs)
        external
        pure
        override
        returns (bool valid)
    {
        // Mock verifier: accept all proofs with valid public inputs
        // In production, replace this with actual verification logic from Noir
        require(publicInputs.length > 0, "MockZKVerifier: invalid public inputs");
        
        // For testing, we can add basic validation
        // In real implementation, this would verify the ZK proof using the verifier contract
        return true;
    }
}

/// @title StrictMockZKVerifier
/// @notice Mock verifier that performs basic validation for testing
/// @dev Validates that public inputs match expected format
contract StrictMockZKVerifier is IZKVerifier {
    /// @notice Verification with basic validation
    /// @param proof The serialized proof bytes
    /// @param publicInputs The public inputs (must contain threshold)
    /// @return valid Returns true if public inputs are valid
    function verify(bytes calldata proof, uint256[] calldata publicInputs)
        external
        pure
        override
        returns (bool valid)
    {
        // Basic validation: check public inputs format
        require(publicInputs.length > 0, "StrictMockZKVerifier: invalid public inputs");
        require(proof.length > 0, "StrictMockZKVerifier: invalid proof");
        
        // In real implementation, this would verify the actual ZK proof
        // For now, we just validate that inputs are present and in correct format
        uint256 threshold = publicInputs[0];
        require(threshold > 0, "StrictMockZKVerifier: threshold must be positive");
        
        return true;
    }
}

